//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Problem_5_6_ATM_Withdrawal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsHistory
    {
        public int Id { get; set; }
        public string CardNumber { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
    }
}
